const date = { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" };
const timestamp = { type: "string", format: "date-time" };
const id = { type: "string", minLength: 1, maxLength: 256 };
const url = { type: ["string", "null"], description: "Verified HTTPS Google Calendar event URL, or null if unavailable." };
const calendar = { type: "object", properties: { id, name: { type: "string", minLength: 1, maxLength: 100 } }, required: ["id", "name"], additionalProperties: false };
const event = { type: "object", properties: { id, calendarId: id, title: { type: "string", maxLength: 500 }, allDay: { type: "boolean" }, start: { type: "string", description: "YYYY-MM-DD for all-day, RFC3339 with offset for timed events." }, end: { type: "string", description: "Exclusive YYYY-MM-DD end for all-day, RFC3339 with offset for timed events." }, url }, required: ["id", "calendarId", "title", "allDay", "start", "end", "url"], additionalProperties: false };
export const calendarTools = [
  { name: "get_calendar_context", description: "Read the signed-in user's saved calendar snapshot, configured calendar IDs and task↔event links. This reads Life Board storage; it does not fetch Google Calendar. Read before imports or linked calendar writes.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, openWorldHint: false } },
  { name: "replace_calendar_snapshot", description: "Save a complete, successfully fetched Google Calendar snapshot for the user's selected calendars. Read all result pages first. Events stay separate from Kanban tasks; do not infer appointment completion. This stores supplied data and does not call Google Calendar. Refresh only within the user's requested scope; do not invent recurring refreshes. expectedRevision is 0 for the first import, otherwise the current snapshot revision. Preserve configured source IDs and task destination on later refreshes.", inputSchema: { type: "object", properties: { expectedRevision: { type: "integer", minimum: 0 }, complete: { type: "boolean", const: true }, calendars: { type: "array", items: calendar, minItems: 1, maxItems: 2 }, writeCalendarId: id, windowStart: timestamp, windowEnd: timestamp, timezone: { type: "string", description: "Verified IANA timezone for the bounded upcoming-14-day window." }, sourceCheckedAt: timestamp, events: { type: "array", items: event, maxItems: 200 } }, required: ["expectedRevision", "complete", "calendars", "writeCalendarId", "windowStart", "windowEnd", "timezone", "sourceCheckedAt", "events"], additionalProperties: false }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false } },
  { name: "mark_calendar_snapshot_stale", description: "After a failed or incomplete requested calendar refresh, retain the last good snapshot and mark it stale. Use its current revision; do not replace it with an empty or partial result. This changes only Life Board metadata.", inputSchema: { type: "object", properties: { expectedRevision: { type: "integer", minimum: 1 }, message: { type: "string", minLength: 1, maxLength: 300 } }, required: ["expectedRevision", "message"], additionalProperties: false }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false } },
  { name: "save_task_calendar_link", description: "Record the verified Google Calendar entry created/updated for one owned task after an explicit per-task user request. This does not create or update Google Calendar. Use the configured Tasks destination, one non-blocking all-day date, no attendees or extra reminders. Read existing links before any external write; existing calendar/event identity is immutable. sourceTaskRevision is the task version actually exported. If the task changed during the external write, record the verified event rather than losing its ID; the UI marks title/date differences as needing a calendar update. expectedLinkRevision is 0 for a new link or its current revision. Do not delete events on archive/completion, or infer appointment completion from elapsed time.", inputSchema: { type: "object", properties: { taskId: { type: "string", format: "uuid" }, expectedLinkRevision: { type: "integer", minimum: 0 }, calendarId: id, eventId: id, url, sourceTaskRevision: { type: "integer", minimum: 1 }, syncedTitle: { type: "string", minLength: 1, maxLength: 200 }, syncedDueDate: date, startDate: date, endDate: date }, required: ["taskId", "expectedLinkRevision", "calendarId", "eventId", "url", "sourceTaskRevision", "syncedTitle", "syncedDueDate", "startDate", "endDate"], additionalProperties: false }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false } },
];
